version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: flight_booking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"

  tracking-service:
    build: ./tracking-service
    container_name: tracking_service
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/flight_tracking_db
    depends_on:
      - mongo